---
# this is a list of the product names available in the shop
# this is used for searching specific product pages etc.
product_names:
  - Can of Oil
  - Dexterous Thin Leg
  - Varied Nuts & Bolts
  - Versatile Thin Arm