---
# this is a list of the product names available in the shop
# this is used for searching specific product pages etc.
product_names:
  - Can of Oil
  - Dexterous Thin Leg
  - Varied Nuts & Bolts
  - Versatile Thin Arm

# # list of product name in the urls (the bit after https://happy-robot.nimbus.fi/product/)
# product_namesinurl:
#   - dexterous-thin-leg/
#   - varied-nuts-bolts/
#   - versatile-thin-arm/
#   - can-of-oil/